project:
  type: website
  output-dir: _site

website:
  title: "imfp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/demo.qmd
        text: Demo
    right:
      - icon: github
        href: https://github.com/Promptly-Technologies-LLC/imfp
  page-footer:
    left: "Copyright 2024, Promptly Technologies, LLC. MIT License."
    right:
      - icon: github
        href: https://github.com/Promptly-Technologies-LLC/imfp

format:
  html:
    theme: cosmo
    toc: true
