project:
  type: website
  output-dir: _site

website:
  title: "imfp"
  search: true
  navbar:
    left:
      - text: Quickstart
        href: index.qmd
      - text: Docs
        menu:
          - text: Installation
            href: docs/installation.qmd
          - text: Databases
            href: docs/databases.qmd
          - text: Parameters
            href: docs/parameters.qmd
          - text: Datasets
            href: docs/datasets.qmd
          - text: Usage
            href: docs/usage.qmd
          - text: Demo
            href: docs/demo.qmd
    right:
      - icon: github
        href: https://github.com/Promptly-Technologies-LLC/imfp
  page-footer:
    left: "Copyright 2024, Promptly Technologies, LLC. MIT License."
    right:
      - icon: github
        href: https://github.com/Promptly-Technologies-LLC/imfp

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true