name: build-test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
        poetry-version: [latest]
        os: [windows-latest, ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Install project
        run: |
          poetry install --no-interaction
      - name: Run tests with pytest
        run: |
          source .venv/scripts/activate
          pytest --version
          pytest tests
        if: runner.os == 'Windows'
      - name: Activate venv other
        run: |
          source .venv/bin/activate
          pytest --version
          pytest tests
        if: runner.os != 'Windows'
