name: format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: rickstaa/action-black@v1
        with:
          black_args: "."

      - name: Commit and push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated code format'
