name: release

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: true
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.16.1
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}